CREATE TABLE IF NOT EXISTS stock_basic (
  dm VARCHAR(10) PRIMARY KEY COMMENT '纯数字代码',
  mc VARCHAR(50) COMMENT '名称',
  jys VARCHAR(5) COMMENT '交易所 SZ/SH/BJ',
  ltsz DECIMAL(20,2) COMMENT '流通市值',
  zsz DECIMAL(20,2) COMMENT '总市值',
  pe DECIMAL(10,2) COMMENT '市盈率',
  pb DECIMAL(10,2) COMMENT '市净率',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS daily_kline (
  dm VARCHAR(10) NOT NULL COMMENT '纯数字代码',
  t DATE NOT NULL COMMENT '交易日',
  o DECIMAL(10,2), h DECIMAL(10,2), l DECIMAL(10,2), c DECIMAL(10,2),
  v BIGINT COMMENT '成交量(手)',
  a DECIMAL(20,2) COMMENT '成交额(元)',
  pc DECIMAL(10,2) COMMENT '昨收',
  ma5 DECIMAL(10,2), ma10 DECIMAL(10,2), ma20 DECIMAL(10,2), ma60 DECIMAL(10,2),
  PRIMARY KEY (dm, t)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
